apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-tello-0
spec:
  containers:
  - name: vkubelet-tello-0
    image: virtual-kubelet
    # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
    imagePullPolicy: IfNotPresent
    args:
    - /virtual-kubelet
    - --nodename
    - vkubelet-tello-0
    - --provider
    - tello
    ports:
    - name: metrics
      containerPort: 10255
    readinessProbe:
      httpGet:
        path: /stats/summary
        port: metrics
  serviceAccountName: virtual-kubelet
