// Code generated by "stringer -type input"; DO NOT EDIT.

package tello

import "strconv"

const _input_name = "tryConnectionconnectionMadetakeOffatHeightflightTimeOverlandonGroundhaltconnectionLostdoneinputSize"

var _input_index = [...]uint8{0, 13, 27, 34, 42, 56, 60, 68, 72, 86, 90, 99}

func (i input) String() string {
	if i < 0 || i >= input(len(_input_index)-1) {
		return "input(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _input_name[_input_index[i]:_input_index[i+1]]
}
