// Code generated by "stringer -type state"; DO NOT EDIT.

package tello

import "strconv"

const _state_name = "disconnectedconnectedtakingOffreadylandingstateSize"

var _state_index = [...]uint8{0, 12, 21, 30, 35, 42, 51}

func (i state) String() string {
	if i < 0 || i >= state(len(_state_index)-1) {
		return "state(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _state_name[_state_index[i]:_state_index[i+1]]
}
